### ISSUE TITLE
Not compatible with Puma web server

### ISSUE THREAD

**Issue by BirknerAlex** [castle/ruby-u2f#27] opened 2017-02-19 23:43 UTC
We've running a Rails 4 project with Puma as web server. After installing the Gem the server can't start anymore. It seems like something overrides the System class.

Only gem uninstall u2f can fix this issue at the moment, I will try to exactly locate the issue in my env.

```
/usr/local/rvm/gems/ruby-2.3.3/gems/system-0.1.3/lib/system.rb:23:in `<class:System>': undefined local variable or method `is_versioned' for System:Class (NameError)
        from /usr/local/rvm/gems/ruby-2.3.3/gems/system-0.1.3/lib/system.rb:22:in `<top (required)>'
        from config/puma.rb:1:in `require'
        from config/puma.rb:1:in `_load_from'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/puma-2.15.3/lib/puma/dsl.rb:20:in `instance_eval'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/puma-2.15.3/lib/puma/dsl.rb:20:in `_load_from'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/puma-2.15.3/lib/puma/dsl.rb:9:in `block in load'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/puma-2.15.3/lib/puma/dsl.rb:8:in `tap'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/puma-2.15.3/lib/puma/dsl.rb:8:in `load'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/puma-2.15.3/lib/puma/configuration.rb:57:in `load'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/puma-2.15.3/lib/puma/cli.rb:543:in `parse_options'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/puma-2.15.3/lib/puma/cli.rb:189:in `run'
        from /usr/local/rvm/gems/ruby-2.3.3/gems/puma-2.15.3/bin/puma:10:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.3/bin/puma:22:in `load'
        from /usr/local/rvm/gems/ruby-2.3.3/bin/puma:22:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

I'm not sure yet but I think the sample Rails project is breaking my Rails project. If I only copy your lib folder to my lib/ directory the u2f library is working fine.

**Comment by bdewater** [comment] 2017-03-03 18:25
It's working just fine for me with Ruby 2.3.3, Rails 5 and Puma 3.6.0. Neither puma or u2f declare a dependency on the system gem so this seems to be caused by your environment.

**Comment by wallin** [comment] 2017-10-31 18:42
Hey, let me know if this is still an issue. I'll be closing this otherwise

**Closed** 2018-09-03 04:51 UTC
